/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

/**
 *
 * @author Benjamín
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    RegistroObras registroObr; 
    
    RegistroTrabajadores registroTra;
    
    public InterfazGrafica(RegistroTrabajadores registroTra, RegistroObras registroObr ) {
        this.registroObr = registroObr;
        this.registroTra = registroTra;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarObraFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextPresupuesto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextTiempoAsignado = new javax.swing.JTextField();
        Región1 = new javax.swing.JComboBox<>();
        jTextNombreObra = new javax.swing.JTextField();
        agregarObraAlSistema = new javax.swing.JButton();
        OpcionesPrincipalesFrame = new javax.swing.JFrame();
        GestionObras = new javax.swing.JButton();
        GestiónEmpleados = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        GestionObrasFrame = new javax.swing.JFrame();
        botonAgregarObra = new javax.swing.JButton();
        botonMostrarAllObras = new javax.swing.JButton();
        botonObraTerminada = new javax.swing.JButton();
        cambiarPresupuesto = new javax.swing.JButton();
        tiempoRestanteDeUnaObra = new javax.swing.JButton();
        gastosTotalesDeUnaObra = new javax.swing.JButton();
        GestiónEmpleadosFrame = new javax.swing.JFrame();
        anadirEmpleadoToPlataforma = new javax.swing.JButton();
        mostrarEmpleadosDeUnaObra = new javax.swing.JButton();
        mostrarTodosLosEmpleados = new javax.swing.JButton();
        moverEmpleados = new javax.swing.JButton();
        despedirEmpleados = new javax.swing.JButton();
        eliminarEmpleadoDePlataforma = new javax.swing.JButton();
        cambiarSueldoDeEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        NombreProyecto = new javax.swing.JLabel();
        Autores = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("Nombre de La Obra");

        jLabel7.setText("Región");

        jTextPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPresupuestoActionPerformed(evt);
            }
        });

        jLabel8.setText("Presupuesto");

        jLabel9.setText("Tiempo asignado");

        Región1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarapaca", "Antofagasta", "Atacama", "Coquimbo", "Valparaiso", "O'higgins", "Maule", "Biobio", "Araucania", "Los Lagos", "Aysen", "Magallanes", "Metropolitana", "Los Rios", "Arica y Parinacota", "Ñuble" }));
        Región1.setToolTipText("");
        Región1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Región1ItemStateChanged(evt);
            }
        });
        Región1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Región1ActionPerformed(evt);
            }
        });

        jTextNombreObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreObraActionPerformed(evt);
            }
        });

        agregarObraAlSistema.setText("Agregar Obra");
        agregarObraAlSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarObraAlSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarObraFrame1Layout = new javax.swing.GroupLayout(agregarObraFrame1.getContentPane());
        agregarObraFrame1.getContentPane().setLayout(agregarObraFrame1Layout);
        agregarObraFrame1Layout.setHorizontalGroup(
            agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarObraFrame1Layout.createSequentialGroup()
                .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarObraFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agregarObraFrame1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jTextNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Región1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83)
                        .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jTextPresupuesto)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jTextTiempoAsignado)))
                    .addGroup(agregarObraFrame1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(agregarObraAlSistema)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        agregarObraFrame1Layout.setVerticalGroup(
            agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarObraFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarObraFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Región1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTiempoAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(agregarObraAlSistema)
                .addGap(51, 51, 51))
        );

        GestionObras.setText("Gestión de Obras");
        GestionObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionObrasActionPerformed(evt);
            }
        });

        GestiónEmpleados.setText("Gestión de Empleados");
        GestiónEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónEmpleadosActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpcionesPrincipalesFrameLayout = new javax.swing.GroupLayout(OpcionesPrincipalesFrame.getContentPane());
        OpcionesPrincipalesFrame.getContentPane().setLayout(OpcionesPrincipalesFrameLayout);
        OpcionesPrincipalesFrameLayout.setHorizontalGroup(
            OpcionesPrincipalesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesPrincipalesFrameLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(OpcionesPrincipalesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GestionObras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GestiónEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        OpcionesPrincipalesFrameLayout.setVerticalGroup(
            OpcionesPrincipalesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesPrincipalesFrameLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(GestionObras)
                .addGap(55, 55, 55)
                .addComponent(GestiónEmpleados)
                .addGap(55, 55, 55)
                .addComponent(Salir)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        botonAgregarObra.setText("Agregar Obra");
        botonAgregarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarObraActionPerformed(evt);
            }
        });

        botonMostrarAllObras.setText("Mostrar Todas Las Obras");
        botonMostrarAllObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarAllObrasActionPerformed(evt);
            }
        });

        botonObraTerminada.setText("Obra Terminada");

        cambiarPresupuesto.setText("Cambiar Presupuesto");

        tiempoRestanteDeUnaObra.setText("Tiempo restante de una Obra");

        gastosTotalesDeUnaObra.setText("Gastos Totales de Una Obra");
        gastosTotalesDeUnaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosTotalesDeUnaObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GestionObrasFrameLayout = new javax.swing.GroupLayout(GestionObrasFrame.getContentPane());
        GestionObrasFrame.getContentPane().setLayout(GestionObrasFrameLayout);
        GestionObrasFrameLayout.setHorizontalGroup(
            GestionObrasFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionObrasFrameLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(GestionObrasFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tiempoRestanteDeUnaObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregarObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMostrarAllObras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cambiarPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonObraTerminada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastosTotalesDeUnaObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        GestionObrasFrameLayout.setVerticalGroup(
            GestionObrasFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionObrasFrameLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(botonAgregarObra)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarAllObras)
                .addGap(18, 18, 18)
                .addComponent(cambiarPresupuesto)
                .addGap(18, 18, 18)
                .addComponent(botonObraTerminada)
                .addGap(18, 18, 18)
                .addComponent(tiempoRestanteDeUnaObra)
                .addGap(18, 18, 18)
                .addComponent(gastosTotalesDeUnaObra)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        anadirEmpleadoToPlataforma.setText("Añadir Empleado a la Plataforma");
        anadirEmpleadoToPlataforma.setMaximumSize(new java.awt.Dimension(109, 23));
        anadirEmpleadoToPlataforma.setMinimumSize(new java.awt.Dimension(109, 23));
        anadirEmpleadoToPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirEmpleadoToPlataformaActionPerformed(evt);
            }
        });

        mostrarEmpleadosDeUnaObra.setText("Mostrar Empleados de una obra");
        mostrarEmpleadosDeUnaObra.setMaximumSize(new java.awt.Dimension(109, 23));
        mostrarEmpleadosDeUnaObra.setMinimumSize(new java.awt.Dimension(109, 23));
        mostrarEmpleadosDeUnaObra.setPreferredSize(new java.awt.Dimension(109, 23));
        mostrarEmpleadosDeUnaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEmpleadosDeUnaObraActionPerformed(evt);
            }
        });

        mostrarTodosLosEmpleados.setText("Mostrar todos los Empleados");

        moverEmpleados.setText("Mover Empleados");

        despedirEmpleados.setText("Despedir Empleados");

        eliminarEmpleadoDePlataforma.setText("Eliminar Empleado de la plataforma");

        cambiarSueldoDeEmpleado.setText("Cambiar Sueldo de un Empleado");

        javax.swing.GroupLayout GestiónEmpleadosFrameLayout = new javax.swing.GroupLayout(GestiónEmpleadosFrame.getContentPane());
        GestiónEmpleadosFrame.getContentPane().setLayout(GestiónEmpleadosFrameLayout);
        GestiónEmpleadosFrameLayout.setHorizontalGroup(
            GestiónEmpleadosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestiónEmpleadosFrameLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(GestiónEmpleadosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarEmpleadosDeUnaObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anadirEmpleadoToPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostrarTodosLosEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moverEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(despedirEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarEmpleadoDePlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cambiarSueldoDeEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        GestiónEmpleadosFrameLayout.setVerticalGroup(
            GestiónEmpleadosFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestiónEmpleadosFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anadirEmpleadoToPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarEmpleadosDeUnaObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarTodosLosEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moverEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(despedirEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarEmpleadoDePlataforma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cambiarSueldoDeEmpleado)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 203, 123));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 275));

        NombreProyecto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        NombreProyecto.setText("Gestión de Obras");
        NombreProyecto.setPreferredSize(new java.awt.Dimension(126, 22));

        Autores.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Autores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Autores.setText("Proyecto Creado por: Andrés Vidal Soto Benjamín Rojas Henríquez");
        Autores.setToolTipText("");

        jButton1.setText("Siguiente");
        jButton1.setPreferredSize(new java.awt.Dimension(78, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Autores, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(NombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Autores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreObraActionPerformed

    private void Región1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Región1ActionPerformed
        // TODO add your handling code here:
       // String coco =(String) this.Región1.getSelectedItem();
        //System.out.println(coco);
    }//GEN-LAST:event_Región1ActionPerformed

    private void Región1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Región1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Región1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        OpcionesPrincipalesFrame.setVisible(true);
        OpcionesPrincipalesFrame.setSize(450,450);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GestionObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionObrasActionPerformed
        // TODO add your handling code here:
        this.OpcionesPrincipalesFrame.setVisible(false);
        this.GestionObrasFrame.setVisible(true);
        //jFrame2.setVisible(rootPaneCheckingEnabled);
        this.GestionObrasFrame.setSize(450,450);        
    }//GEN-LAST:event_GestionObrasActionPerformed

    private void anadirEmpleadoToPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirEmpleadoToPlataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anadirEmpleadoToPlataformaActionPerformed

    private void mostrarEmpleadosDeUnaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEmpleadosDeUnaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarEmpleadosDeUnaObraActionPerformed

    private void gastosTotalesDeUnaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosTotalesDeUnaObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastosTotalesDeUnaObraActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void GestiónEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónEmpleadosActionPerformed
        // TODO add your handling code here:
        //this.OpcionesPrincipalesFrame.setVisible(false);
        this.GestiónEmpleadosFrame.setVisible(true);
        GestiónEmpleadosFrame.setSize(450, 450);
    }//GEN-LAST:event_GestiónEmpleadosActionPerformed

    private void botonAgregarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarObraActionPerformed
        // TODO add your handling code here:
        this.GestionObrasFrame.setVisible(false);
        this.agregarObraFrame1.setVisible(true);
        this.agregarObraFrame1.setSize(450, 450);
    }//GEN-LAST:event_botonAgregarObraActionPerformed

    private void jTextPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPresupuestoActionPerformed

    private void agregarObraAlSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarObraAlSistemaActionPerformed
        // TODO add your handling code here:
        String nombreObra = this.jTextNombreObra.getText();
        String region = (String) this.Región1.getSelectedItem();
        int presupuesto = Integer.parseInt(this.jTextPresupuesto.getText());
        String tiempoAsignado = this.jTextTiempoAsignado.getText();
        
        Obra obraAgregar = new Obra(nombreObra,region,presupuesto,tiempoAsignado);
        
        this.registroObr.agregarObra(obraAgregar);
        
        System.out.println("Obra Añadida al sistema");
        System.out.println(nombreObra);
        System.out.println(region);
        System.out.println(presupuesto);
        System.out.println(tiempoAsignado);
        
    }//GEN-LAST:event_agregarObraAlSistemaActionPerformed

    private void botonMostrarAllObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarAllObrasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonMostrarAllObrasActionPerformed

    
    
    /**
     * @param args the command line arguments

     */
    
    
    
    public static void main(String args[]) {
        //registroTrabajadores.mostrarEspecialistas("Informático");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica(new RegistroTrabajadores(),new RegistroObras()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autores;
    private javax.swing.JButton GestionObras;
    private javax.swing.JFrame GestionObrasFrame;
    private javax.swing.JButton GestiónEmpleados;
    private javax.swing.JFrame GestiónEmpleadosFrame;
    private javax.swing.JLabel NombreProyecto;
    private javax.swing.JFrame OpcionesPrincipalesFrame;
    private javax.swing.JComboBox<String> Región1;
    private javax.swing.JButton Salir;
    private javax.swing.JButton agregarObraAlSistema;
    private javax.swing.JFrame agregarObraFrame1;
    private javax.swing.JButton anadirEmpleadoToPlataforma;
    private javax.swing.JButton botonAgregarObra;
    private javax.swing.JButton botonMostrarAllObras;
    private javax.swing.JButton botonObraTerminada;
    private javax.swing.JButton cambiarPresupuesto;
    private javax.swing.JButton cambiarSueldoDeEmpleado;
    private javax.swing.JButton despedirEmpleados;
    private javax.swing.JButton eliminarEmpleadoDePlataforma;
    private javax.swing.JButton gastosTotalesDeUnaObra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextNombreObra;
    private javax.swing.JTextField jTextPresupuesto;
    private javax.swing.JTextField jTextTiempoAsignado;
    private javax.swing.JButton mostrarEmpleadosDeUnaObra;
    private javax.swing.JButton mostrarTodosLosEmpleados;
    private javax.swing.JButton moverEmpleados;
    private javax.swing.JButton tiempoRestanteDeUnaObra;
    // End of variables declaration//GEN-END:variables
}
